export const METAMASK_NOT_INSTALLED = "METAMASK_NOT_INSTALLED";
export const NOT_ENABLED = "NOT_ENABLED";
export const REQUEST_GET_CONTRACTS_FAIL = "REQUEST_GET_CONTRACTS_FAIL";
export const CHAIN_ID_NOT_FOUND = "CHAIN_ID_NOT_FOUND";
export const DEFAULT_ADDRESS_NOT_FOUND = "DEFAULT_ADDRESS_NOT_FOUND";
export const QR_CODE_HANDLER_NOT_SET = "QR_CODE_HANDLER_NOT_SET";

export const REQUEST_ALREADY_PROCESSED = "REQUEST_ALREADY_PROCESSED";
export const MESSAGE_REQ_PROCESSED = "Already processing eth_requestAccounts";
export const FAILURE_RECEIPT_STATUS = "FAILURE_RECEIPT_STATUS";

export const PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND";
export const PROPOSALS_NOT_FOUND = "PROPOSALS_NOT_FOUND";
export const SWAP_ONEINCH_FAIL = "SWAP_ONEINCH_FAIL";
export const TOKENS_LIST_NOT_ACCESS = "TOKENS_LIST_NOT_ACCESS";

export const INSUFFICIENT_LIQUIDITY = "INSUFFICIENT_LIQUIDITY";
