/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { AdminRoleContract } from "./AdminRole";
import { DaoRoleContract } from "./DaoRole";
import { DetfContract } from "./Detf";
import { DetfReflectContract } from "./DetfReflect";
import { GovernorContract } from "./Governor";
import { GovernorEventsContract } from "./GovernorEvents";
import { GovernorProxyContract } from "./GovernorProxy";
import { GovernorStorageContract } from "./GovernorStorage";
import { IDetfContract } from "./IDetf";
import { Ierc20Contract } from "./Ierc20";
import { Ierc20DetailedContract } from "./Ierc20Detailed";
import { Ierc20MetadataContract } from "./Ierc20Metadata";
import { ITokenTimelockContract } from "./ITokenTimelock";
import { IUniswapV2FactoryContract } from "./IUniswapV2Factory";
import { IUniswapV2PairContract } from "./IUniswapV2Pair";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { OwnableContract } from "./Ownable";
import { PoolContract } from "./Pool";
import { TimelockContract } from "./Timelock";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "AdminRole"): AdminRoleContract;
      require(name: "DaoRole"): DaoRoleContract;
      require(name: "Detf"): DetfContract;
      require(name: "DetfReflect"): DetfReflectContract;
      require(name: "Governor"): GovernorContract;
      require(name: "GovernorEvents"): GovernorEventsContract;
      require(name: "GovernorProxy"): GovernorProxyContract;
      require(name: "GovernorStorage"): GovernorStorageContract;
      require(name: "IDetf"): IDetfContract;
      require(name: "IERC20"): Ierc20Contract;
      require(name: "IERC20Detailed"): Ierc20DetailedContract;
      require(name: "IERC20Metadata"): Ierc20MetadataContract;
      require(name: "ITokenTimelock"): ITokenTimelockContract;
      require(name: "IUniswapV2Factory"): IUniswapV2FactoryContract;
      require(name: "IUniswapV2Pair"): IUniswapV2PairContract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "Ownable"): OwnableContract;
      require(name: "Pool"): PoolContract;
      require(name: "Timelock"): TimelockContract;
    }
  }
}

export { AdminRoleContract, AdminRoleInstance } from "./AdminRole";
export { DaoRoleContract, DaoRoleInstance } from "./DaoRole";
export { DetfContract, DetfInstance } from "./Detf";
export { DetfReflectContract, DetfReflectInstance } from "./DetfReflect";
export { GovernorContract, GovernorInstance } from "./Governor";
export {
  GovernorEventsContract,
  GovernorEventsInstance
} from "./GovernorEvents";
export { GovernorProxyContract, GovernorProxyInstance } from "./GovernorProxy";
export {
  GovernorStorageContract,
  GovernorStorageInstance
} from "./GovernorStorage";
export { IDetfContract, IDetfInstance } from "./IDetf";
export { Ierc20Contract, Ierc20Instance } from "./Ierc20";
export {
  Ierc20DetailedContract,
  Ierc20DetailedInstance
} from "./Ierc20Detailed";
export {
  Ierc20MetadataContract,
  Ierc20MetadataInstance
} from "./Ierc20Metadata";
export {
  ITokenTimelockContract,
  ITokenTimelockInstance
} from "./ITokenTimelock";
export {
  IUniswapV2FactoryContract,
  IUniswapV2FactoryInstance
} from "./IUniswapV2Factory";
export {
  IUniswapV2PairContract,
  IUniswapV2PairInstance
} from "./IUniswapV2Pair";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance
} from "./IUniswapV2Router02";
export { OwnableContract, OwnableInstance } from "./Ownable";
export { PoolContract, PoolInstance } from "./Pool";
export { TimelockContract, TimelockInstance } from "./Timelock";
